.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "PUPPET\-DESCRIBE" "8" "January 2025" "Vox Pupuli" "OpenVox manual"
.SH "NAME"
\fBpuppet\-describe\fR \- Display help about resource types available to OpenVox
.SH "SYNOPSIS"
Prints help about Puppet resource types, providers, and metaparameters installed on an OpenVox node\.
.SH "USAGE"
puppet describe [\-h|\-\-help] [\-s|\-\-short] [\-p|\-\-providers] [\-l|\-\-list] [\-m|\-\-meta]
.SH "OPTIONS"
.TP
\-\-help
Print this help text
.TP
\-\-providers
Describe providers in detail for each type
.TP
\-\-list
List all types
.TP
\-\-meta
List all metaparameters
.TP
\-\-short
List only parameters without detail
.SH "EXAMPLE"
.nf
$ puppet describe \-\-list
$ puppet describe file \-\-providers
$ puppet describe user \-s \-m
.fi
.SH "AUTHOR"
David Lutterkort
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Inc\. Copyright (c) 2024 Vox Pupuli Licensed under the Apache 2\.0 License
