.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "PUPPET" "8" "January 2025" "Vox Pupuli" "OpenVox manual"
.SH "NAME"
\fBpuppet\fR \- OpenVox is an automated configuration management tool
.SH "SYNOPSIS"
\fBpuppet\fR \fIsubcommand\fR [options] \fIaction\fR [options]
.SH "DESCRIPTION"
OpenVox is a community implementation of Puppet, an automated administrative engine for your Linux, Unix, and Windows systems, designed to perform administrative tasks (such as adding users, installing packages, and updating server configurations) based on a centralized specification\.
.SH "COMMANDS"
.SS "Common"
\fBapply\fR
.br
\~\~\~\~Apply Puppet manifests locally via OpenVox
.P
\fBagent\fR
.br
\~\~\~\~The puppet agent daemon provided by OpenVox
.P
\fBconfig\fR
.br
\~\~\~\~Interact with OpenVox's settings\.
.P
\fBhelp\fR
.br
\~\~\~\~Display OpenVox help\.
.P
\fBlookup\fR
.br
\~\~\~\~Interactive Hiera lookup for OpenVox
.P
\fBmodule\fR
.br
\~\~\~\~Creates, installs and searches for modules on the Puppet Forge\.
.P
\fBresource\fR
.br
\~\~\~\~The OpenVox resource abstraction layer shell
.SS "Specialized"
\fBstrings\fR
.br
\~\~\~\~Generate Puppet documentation with YARD\.
.P
\fBcatalog\fR
.br
\~\~\~\~Compile, save, view, and convert catalogs\.
.P
\fBdescribe\fR
.br
\~\~\~\~Display help about resource types available to OpenVox
.P
\fBdevice\fR
.br
\~\~\~\~Manage remote network devices via OpenVox
.P
\fBdoc\fR
.br
\~\~\~\~Generate Puppet references for OpenVox
.P
\fBepp\fR
.br
\~\~\~\~Interact directly with the EPP template parser/renderer\.
.P
\fBfacts\fR
.br
\~\~\~\~Retrieve and store facts\.
.P
\fBfilebucket\fR
.br
\~\~\~\~Store and retrieve files in an OpenVox filebucket
.P
\fBgenerate\fR
.br
\~\~\~\~Generates Puppet code from Ruby definitions\.
.P
\fBnode\fR
.br
\~\~\~\~View and manage node definitions\.
.P
\fBparser\fR
.br
\~\~\~\~Interact directly with the parser\.
.P
\fBplugin\fR
.br
\~\~\~\~Interact with the OpenVox plugin system\.
.P
\fBscript\fR
.br
\~\~\~\~Run a puppet manifests as a script without compiling a catalog
.P
\fBssl\fR
.br
\~\~\~\~Manage SSL keys and certificates for OpenVox SSL clients
.SH "SEE ALSO"
See \fBpuppet help <subcommand>\fR for help on a specific subcommand\.
.P
See \fBpuppet help <subcommand> <action>\fR for help on a specific subcommand action\.
