.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "PUPPET\-DOC" "8" "January 2025" "Vox Pupuli" "OpenVox manual"
.SH "NAME"
\fBpuppet\-doc\fR \- Generate Puppet references for OpenVox
.SH "SYNOPSIS"
Generates a reference for all Puppet types\. Largely meant for internal use\. (Deprecated)
.SH "USAGE"
puppet doc [\-h|\-\-help] [\-l|\-\-list] [\-r|\-\-reference \fIreference\-name\fR]
.SH "DESCRIPTION"
This deprecated command generates a Markdown document to stdout describing all installed Puppet types or all allowable arguments to puppet executables\. It is largely meant for internal use and is used to generate the reference documents which can be posted to a website\.
.P
For Puppet module documentation (and all other use cases) this command has been superseded by the "puppet\-strings" module \- see https://github\.com/puppetlabs/puppetlabs\-strings for more information\.
.P
This command (puppet\-doc) will be removed once the puppetlabs internal documentation processing pipeline is completely based on puppet\-strings\.
.SH "OPTIONS"
.TP
\-\-help
Print this help message
.TP
\-\-reference
Build a particular reference\. Get a list of references by running 'puppet doc \-\-list'\.
.SH "EXAMPLE"
.nf
$ puppet doc \-r type > /tmp/type_reference\.markdown
.fi
.SH "AUTHOR"
Luke Kanies
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Inc\. Copyright (c) 2024 Vox Pupuli Licensed under the Apache 2\.0 License
